version: "3.8"

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "29092"
    depends_on:
      - zookeeper
    networks:
      - kafka_network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      
  tweetapp:
    image: manimaran6483/tweetapp-final:v1
    container_name: tweetapp
    links:
      - zookeeper
      - kafka
    depends_on:
      - kafka
    ports:
      - "8082:8081"
    networks:
      - kafka_network
    volumes:
      - ./config/logs:/config/logs
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      LOGGING_FILE_NAME: ./config/log/tweetApp.log
    build:
      context: ./
      dockerfile: Dockerfile

networks:
  kafka_network:
    driver: bridge
